---
version: '2.1'
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:z
    logging:
      driver: "json-file"
      options:
       max-size: 100m
    ports:
      - "9090:9090"
