---
version: '2.1'
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    volumes:
    - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:z
    logging:
      driver: "json-file"
      options:
       max-size: 100m
    ports:
      - "9090:9090"

  grafana:
    image: docker.io/grafana/grafana:latest
    depends_on:
    - prometheus
    volumes:
    - ./grafana.ini:/etc/grafana/grafana.ini
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    ports:
      - "3001:3000"
